---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Repositório principal do curso "Criação de Dashboards Interativos com o Shiny"

Baseado no curso [Shiny: Zero a Hero](https://curso-r.github.io/latinr-shiny/)

# Vídeo

- [Gravação no Youtube](https://www.youtube.com/watch?v=25ND51icjIw)

# Material

- [Apresentação](https://predict-icmc.github.io/curso-shiny/slides/slides_latinr_shiny_zero_to_hero.html)
- [Script 1: Olá Mundo](https://predict-icmc.github.io/curso-shiny/scripts/01-ola-mundo.R)
- [Script 2: Output](https://predict-icmc.github.io/curso-shiny/scripts/02-output.R)
- [Script 3: Output e Input](https://predict-icmc.github.io/curso-shiny/scripts/03-output-input.R)
- [Script 4: Plotly](https://predict-icmc.github.io/curso-shiny/scripts/04-plotly.R)
- [Script 5: Leaflet](https://predict-icmc.github.io/curso-shiny/scripts/05-leaflet.R)
- [Script 5: Case: covid-19](https://predict-icmc.github.io/curso-shiny/scripts/06-covid-19.R)
- [Conjunto de dados `vacinados_munic.csv`](https://predict-icmc.github.io/curso-shiny/scripts/vacinados_munic.csv)
- [Conjunto de dados `dados-covid-sp.csv`](https://predict-icmc.github.io/curso-shiny/scripts/dados-covid-sp.csv)

  

# Ementa

- **Introdução ao Shiny**
  - Dashboards estáticos e dinâmicos
  - O que é o Shiny?
  - UI e server
  - Inputs e Outputs
- **Layout**
  - Costumizando a aparência do dashboard
  - O pacote `plot_ly`
- **Dados geolocalizados**
  - Mapas com `leaflet`
- **Deploy**
  - Hospedando um app no `shinyapps.io`

# Outros materiais

## Dashboard criado no evento: 

https://predict-icmc.shinyapps.io/vacina_sp/

## Links citados:

Galeria Shiny:
https://shiny.rstudio.com/gallery/widget-gallery.html

Galeria RMarkdown:
https://rmarkdown.rstudio.com/gallery.html

Shiny Server:
https://rstudio.com/products/shiny/download-server/

Pacote datos:
https://cienciadedatos.github.io/datos/

Youtube da Curso-R:
https://www.youtube.com/c/CursoR6/featured
